let rainbow = [];
rainbow.push("red");
rainbow.push("orange");
rainbow.push("yellow");
rainbow.push("green");
rainbow.push("blue");
rainbow.push("indigo");
rainbow.push("violet");
console.log(rainbow.pop());
console.log(rainbow.pop());
console.log(rainbow.pop());
console.log(rainbow.pop());
console.log(rainbow.pop());
console.log(rainbow.pop());
console.log(rainbow.pop());